name = "Dartis-Craft AxB Kinpack"
author = "Dartis-Craft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e702a97fa2cd18e8daa14bca09adecb0beaf70976616e8d71298f078fbedbb22"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
