name = "Dartis-Craft AxB Kinpack"
author = "Dartis-Craft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c59fe801d1d68925905dd0ff1b37870c798701518a0f74d935a2b035dc58386"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
